dist: trusty
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.4
      env: LARAVEL_FRAMEWORK_VERSION=5.0.*
    - php: 5.5
      env: LARAVEL_FRAMEWORK_VERSION=5.0.*
    - php: 5.5
      env: LARAVEL_FRAMEWORK_VERSION=5.1.*
    - php: 5.5
      env: LARAVEL_FRAMEWORK_VERSION=5.2.*
    - php: 5.6
      env: LARAVEL_FRAMEWORK_VERSION=5.0.*
    - php: 5.6
      env: LARAVEL_FRAMEWORK_VERSION=5.1.*
    - php: 5.6
      env: LARAVEL_FRAMEWORK_VERSION=5.2.*
    - php: 5.6
      env: LARAVEL_FRAMEWORK_VERSION=5.3.*
    - php: 5.6
      env: LARAVEL_FRAMEWORK_VERSION=5.4.*
    - php: 7.0
      env: LARAVEL_FRAMEWORK_VERSION=5.2.*
    - php: 7.0
      env: LARAVEL_FRAMEWORK_VERSION=5.3.*
    - php: 7.0
      env: LARAVEL_FRAMEWORK_VERSION=5.4.*
    - php: 7.0
      env: LARAVEL_FRAMEWORK_VERSION=5.5.*
    - php: 7.1
      env: LARAVEL_FRAMEWORK_VERSION=5.5.*
    - php: 7.2
      env: LARAVEL_FRAMEWORK_VERSION=5.5.*

before_script:
  - composer self-update
  - composer require "illuminate/support:${LARAVEL_FRAMEWORK_VERSION}" --no-update
  - composer require "illuminate/database:${LARAVEL_FRAMEWORK_VERSION}" --no-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
  - ./codeclimate.sh
